### ISSUE TITLE
Can't run task `redwoodGenerate`

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1312]
After pulling the repo, running `./gradlew samples:counter:schema:tasks` lists `redwoodGenerate` as a task. When running `./gradlew samples:counter:schema:redwoodGenerate`, I get the error:

```
* What went wrong:
Cannot locate tasks that match 'samples:counter:schema:redwoodGenerate' as task 'redwoodGenerate' is ambiguous in project ':samples:counter:schema'. Candidates are: 'redwoodApiGenerate', 'redwoodJsonGenerate'.
```

**Comment by JakeWharton** [comment]
This is a Gradle quirk. The `tasks` task will list tasks which are available both on the immediate project, but also aggregated from subprojects. The `redwoodGenerate` task is available in `:samples:counter:schema:compose` and `:samples:counter:schema:widget` but not `:samples:counter:schema` which is why you get that error. If the `redwoodApiGenerate` and `redwoodJsonGenerate` tasks did not exist in the `:samples:counter:schema` project, running `:samples:counter:schema:redwoodGenerate` would likely run both of the `redwoodGenerate` tasks in the two subprojects (the same way you can run `build` at the root and runs `build` on all the subprojects).

We can rename the task to `redwoodKotlinGenerate` simply to match the pattern which will have the side-effect of fixing this quirk, but it's not strictly a Redwood bug.
