### ISSUE TITLE
Android: A Row with 2 children can calculate a size too large for the second child

### ISSUE THREAD

**Issue by ean5533** [cashapp/redwood#2017]
### Summary

On Android, when two children are nested inside a `Row`, and the childrens' combined content are greater than the Row's width, the second child's calculated width will exceed the parent Row's bounds. It looks like the second child's width will grow to match the Row's width, despite the first child taking up some of that space.

Works as expected on iOS.

### Repro

```
Row {
  Spacer(30.dp)
  Text("This is a very long piece of text that will wrap the screen")
}
```

### Screenshots 
![image](https://github.com/cashapp/redwood/assets/1847776/0011f2b0-6df8-4353-859f-5045c64cdc90)

### Attempted tweaks

* Adding `Modifier.shrink()` or `Modifier.flex()` to the second child makes it work as expected.
* Adding `Modifier.grow()` to the second child has no effect

**Comment by swankjesse** [comment]
I’m looking into this and I regret that I think this behavior is working as expected. I also think that’s surprising, so I’d like to explain how I got here...

The `Row` has two child components, and as far as it’s concerned they’re symmetric. Assuming the screen is 200.dp wide and vertically scrolling, the row makes two calls to its two children:

1. `spacer.measure(maxWidth=200.dp, height=any)`, from which the spacer returns `30.dp`
2. `text.measure(maxWidth=200.dp, height=any)`, from which the text returns `200.dp`

When I was investigating this, I was surprised at the argument into the 2nd call. Why didn’t the row offer a `maxWidth=170.dp`, as that’s what’s available?!

But to my surprise the layout doesn’t use a greedy algorithm, hand out space as it traverses through its children. Instead it measures each of them, and then decides how to reconcile the difference if the total doesn’t add up to 200.dp. If the total is lower than 200.dp, it’ll look at the `grow` modifiers and grow its children accordingly. If the total is greater than 200.dp it’ll look at the `shrink` modifiers and shrink its children accordingly.

## Why offer the same pixels to both children?

This kind of makes sense to me, but if the row has 200.dp to allocate to its two children, why offer both of them the whole 200.dp? Why not start from an even split, like so?

1. `spacer.measure(maxWidth=100.dp, height=any)`
2. `text.measure(maxWidth=100.dp, height=any)`

I guess we can reject this because it’d break if the spacer was 101.dp.

Similarly, it won’t work in general it starts with `0.dp` and lets its children decide everything. Consider:

1. `spacer.measure(width=any, height=any)` from which the spacer returns 30.dp
2. `text.measure(width=any, height=any)` from which the text returns the full width of the text _without wrapping_, which might be say, 1000.dp.

In that case the row would need to shrink 30.dp + 1000.dp into 200.dp.

## How I sleep at night

Let’s imagine the spacer was on the right.

```kotlin
Row {
  Text("This is a very long piece of text that will wrap the screen")
  Spacer(30.dp)
}
```

Then the two calls would look like this:

1. `text.measure(maxWidth=200.dp, height=any)`, from which the text returns `200.dp`
2. `spacer.measure(maxWidth=200.dp, height=any)`, from which the spacer returns `30.dp`

This actually makes sense, because it can’t offer `170.dp` to the text because it hasn’t measured the spacer is yet.

It’s much more natural to reconcile this case by configuring `flex` on the text. That’s basically saying, ‘don’t even bother measuring the text, it’ll just take what’s left over’. And that’s what it does.

## How I Think About This

Each child of a row is measured independently. When it is measured it is told the target dimensions for the whole row.

The width of a row is the sum of the widths of its children.

These widths may overflow the width of the screen! But to prevent this, configure a child widget to be flexible.

```kotlin
Row {
  Spacer(30.dp)
  Text(
    modifier = Modifier.flex(1.0),
    text = "This is a very long piece of text that will wrap the screen"
  )
}
```

### What About Columns?

Columns are the same. But often our columns scroll vertically, so the screen height is effectively infinite.
