### ISSUE TITLE
Switch main dispatcher to Main.immediate

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#318]
We’re currently using `Dispatchers.Main` on Android. We will get better performance with `Dispatchers.Main.immediate`.

**Comment by JakeWharton** [comment]
Since this was based on a comment I made I looked into this. We never call a `suspend` function using this dispatcher so it would actually make no difference.

One thing to note, however, is that by using `Dispatchers.Main` for the Android dispatcher we are actually using an async handler which can deliver messages to the UI thread between frame boundaries. This is probably fine, but could be something in the future we look at switching to a vsync-synchronized handler-wrapped-dispatcher instead so as to only deliver things at the start of each frame.
