### ISSUE TITLE
TreehouseView composition local to provide host info to composables

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#355]
I think it’d be useful to have something so in-treehouse UI can query the screen it’s being displayed on.

Perhaps something like this:

```
interface ZiplineFrame : ZiplineService {
  fun screen(): Screen
  fun setGoBackCallback(callback: GoBackCallback?)
}

class Screen(
  val width: Int,
  val height: Int,
  val colorDepth: Int,
  val darkMode: Boolean,
)

interface GoBackCallback: ZiplineService {
  fun goBack()
}
```

(We’ve talked about handling back in issue #324)

**Comment by JakeWharton** [comment]
Definitely don't want to use the "Zipline" name anywhere here and none of these types can extend `ZiplineService`. It's not only an implementation detail but technically you don't have to use it.

In the past we talked about a `DisplayFrame` composition local that had a similar properties. Although we have multiple sizes to contend with: treehouse view size, window size, display size. Other properties I remember talking about are the app locale and the display density.

For back handling I think it makes more sense to be a composable itself so that we automatically get a lifecycle as to when it's active or not. This will allow us to propagate it to the OS on Android for predictive back handling to work correctly. It can talk through a composition local of some manager which can handle register/unregister of the actual callback up into the display.

In Mosaic I'm playing with raw key event handling as a composable for the same reasons.

**Comment by swankjesse** [comment]
Yes to all those things. The types we expose to presenters will be different from the interfaces we bridge.

**Comment by JakeWharton** [comment]
`UiConfiguration` exists with sufficient data now. Additional data can be its own feature request.
