### ISSUE TITLE
Widget IDs

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#371]
I’d like to have a way to refer to widgets in a composition. My specific use case is so I can position a pop-up window adjacent to a widget in a composition. I can also imagine use cases where I use IDs to drive shared element transitions, possibly even transitions that span non-Redwood widgets!

### Compose

Every widget gains a new optional `id` parameter that defaults to null. 

Sample generated code:

```
@Composable
public fun Image(
  url: String, 
  onClick: (() -> Unit)? = null,
  layoutModifier: LayoutModifier = LayoutModifier,
  id: Long? = null,
): Unit { ... }
```

A user gets the ID for a widget by calling a new `nextWidgetId()` function and passing that in. Note that a `remember` call is necessary. 

```
class PopUpTreehouseUi {
  val popUpApplication: PopUpApplication = ...

  @Composable
  override fun Show() {
    val imageId = remember { nextWidgetId() }
    Image(
      url = ...
      id = imageId,
      onClick = {
        popUpApplication.showPopUpBesideWidget(imageId)
      }
    )
  }
```

If no ID is passed in, an ID is generated internally.

### Display

Users can retrieve their platform-specific widget object via the `ProtocolDisplay`.

```
public class ProtocolDisplay<T : Any>(...) : DiffSink {

  /**
   * Returns the widget on the current display for [id], or null if
   * no such widget exists. This may be the case if the widget has
   * since been removed from the display.
   */
  public fun widget(id: Long): T?
}
```

Perhaps the easiest way to make this value accessible to application code is to make another accessor on `TreehouseApp`. We may also want to make that member public on `TreehouseView`.

```
class PopUpApplication(
  val treehouseApp: TreehouseApp<*>,
) : ZiplineService {
  fun showPopUpBesideWidget(id: Long) {
    val imageView = (treehouseApp.widget(id) ?: return) as View
    showPopUp(widget.boundsInWindow())
  }
}
```

### Unique IDs

It’d be convenient to find a way to make widget IDs in the system unique, even if the `TreehouseApp` updates its code while it’s running. Probably the best way to bootstrap this is to make `ProtocolApplier` take its initial ID in its constructor, and to wire that in somehow.

**Comment by JakeWharton** [comment]
Now that I've had a few hours to think about this, I do not think it's a good path forward.

I have a few issues with it, but the biggest is that when using Compose UI to render this approach yields no discernible way to produce a popup. You get back a function reference from the `ProtocolDisplay` that you can't do anything meaningful with.

The way to do this in pure Compose UI is documented here: https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#dropdownmenu. This goes back to what we talked about in keeping it as a node in the normal tree. It also avoids the need to have a side-channel and expose the otherwise implementation-detail ID system to user code which seems like a huge win.

I think it informs both what we probably should do at the composable layer in terms of design (allowing you to define the popup contents locally at the site from which you want to display it, sharing the same state) but also in how we propagate it to the widgets to be rendered.

We can have a node with two children slots like your original design but have the `Widget.Children` implementation show a popup window when non-empty. All children beneath that go into the popup window (still allowing regular recomposition within that slot to update the contents of the window). Options on things like gravity and positioning are properties on the composable and touch-outside/back dismiss is a callback.

```kotlin
@Widget(..)
data class PopupAnchor(
  @Children(1) val children: () -> Unit,
  @Property(1) val popupShown: Boolean,
  @Property(2) val popupGravity: PopupGravity = PopupGravity.BelowOrAbove,
  @Property(2) val popupDismissed: () -> Unit,
  @Children(2) val popupContent: () -> Unit,
)
```

**Comment by swankjesse** [comment]
That works for me, and is a good fit for pop-ups. Any thoughts on shared element transitions? That was the other thing I liked about having an identity for a view.

**Comment by JakeWharton** [comment]
No, but it's probably something close to this original design. However it probably can be totally decoupled from our protocol IDs.

Maybe a layout modifier that takes an arbitrary string key? (Except it's not really a layout modifier it's a normal modifier. We might need a rename!)

It's another thing that I think we want to look at what Compose UI is doing because they'll have the same problems.
