### ISSUE TITLE
EmojiSearch sample needs a TextFieldState type

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#380]
To defend against racy edits.

**Comment by eygraber** [comment]
Is the idea here that a `TextFieldState` would be used in the schema instead of a `String` so that the same state is used throughout the loop (and there's no race where the host ui updates using the old state that it is holding before receiving the new state)?

**Comment by eygraber** [comment]
I took an initial (naive) stab at this, by using a similar implementation to TextController from workflow. It doesn't work, and I imagine the reason is because the updates to the value on the JS side don't propagate through the MutableStateFlow to the Android side.

Is a different approach needed, or is there some way to make the update cross over to Android?

I'll push a branch with my WIP soon

**Comment by JakeWharton** [comment]
We have a copy of this internally that works, at least for view-based widgets which is what we're currently using. I don't think we've ever looked at Workflow or what it does (and I don't quite understand why it has this issue but that's besides the point). I'm not sure how involved it would be to copy it out.

**Comment by eygraber** [comment]
Unless I'm misunderstanding what this issue is for, I didn't see this happen for view-based widgets at all; just the Compose UI one.

**Comment by eygraber** [comment]
And just like that, I started seeing issues with the view based widgets :sweat_smile:

**Comment by JakeWharton** [comment]
Yeah it should happen for both.

**Comment by eygraber** [comment]
Is there any easy way to summarize the internal solution so that I can go running with it, or is it better until you guys figure out how to move it over?

**Comment by colinrtwhite** [comment]
@eygraber Here's how we track the state internally:

```kotlin
@Serializable
data class TextFieldState(
  val text: String = "",
  val selectionStart: Int = 0,
  val selectionEnd: Int = 0,
  val userEditCount: Long = 0L,
)
```

Basically we only update the text field's state if `newState.userEditCount > oldState.userEditCount`. We also need to handle text state updates on `treehouseDispatchers.zipline`.

**Comment by eygraber** [comment]
Started something in https://github.com/eygraber/redwood/tree/380 but ran out of gas in the middle :sleeping: 

I have an [open question about how to handle updates from TextField](https://github.com/eygraber/redwood/commit/a6d99cd710066bbeb92fe6b895432ac6892b5791#diff-d22e8f40abf1b12266f0514a05b05119310abdc7db2a2477a10e35aa6bd86277R39-R43). My guess is that the second approach is correct because otherwise we mess with `TextField` state, but it does lead to two sources of truth.

> We also need handle text state updates on `treehouseDispatchers.zipline`

I'm not familiar enough with the Treehouse system to how that should work. Should that be happening in `ComposeUiTextInput` or `RealEmojiSearchPresenter`?

**Comment by colinrtwhite** [comment]
@eygraber I think you were on the right track! I pulled your changes into [this PR](https://github.com/cashapp/redwood/pull/528) with the remaining bits from our internal implementation.
